name: Release (canary)

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Test & Build
    uses: .github/workflows/test.yaml

  relrease_canary:
    name: Release (canary)
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - run: bun install --frozen-lockfile
      - run: bun run build
      - run: bun run canary
      - name: Setup npm
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          npm config set registry https://registry.npmjs.org/
          npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN
      - run: bun run release
        env:
          NPM_REGISTRY_URL: https://registry.npmjs.org/
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
