on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - run: bun install --frozen-lockfile
      - run: bun run check
      - run: bun test
      - run: bunx changeset version --snapshot canary
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      - run: bun run build
      - name: Setup npm
        env:
          NPM_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          npm config set registry https://npm.pkg.github.com
          npm config set //npm.pkg.github.com/:_authToken $NPM_TOKEN
      - run: bun run release
        env:
          NPM_REGISTRY_URL: https://npm.pkg.github.com
          NPM_TOKEN: ${{ secrets.GH_TOKEN }}
