name: Release (next)

on:
  workflow_run:
    workflows: ["Run Tests"]
    branches:
      - next
    types:
      - completed

jobs:
  canary:
    name: Build & Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - run: bun install --frozen-lockfile
      - run: bun run build
      - run: bun run canary -- next
      - name: Setup npm
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          npm config set registry https://registry.npmjs.org/
          npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN
      - run: bun run release
        env:
          NPM_REGISTRY_URL: https://registry.npmjs.org/
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
