name: Release (main)

on:
  push:
    branches:
      - main

jobs:
  release_main:
    name: Build & Release
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - run: echo "🚀 Release workflow triggered TODO"
